**MAESTRÍA EN INTELIGENCIA ARTIFICIAL APLICADA**

**Curso: TC5053 - Ciencia y analítica de datos**

Tecnológico de Monterrey

Prof Grettel Barceló Alonso

**Semana 3**
Bases, almacenes y manipulación de datos

---

*   NOMBRE:  ITALO JAVIER CONTRERAS PEREZ
*   MATRÍCULA: A01841252

---

En esta actividad usarás una base de datos relacional basada en el informe de participación y la lista del top 10 de Netflix. Incluye películas y programas de televisión, así como información sobre temporadas, métricas de visualización, fechas de estreno, duración y más, organizada en las siguientes tablas:

* `movie`: Información general de las películas.

* `tv_show`: Información general de los programas de televisión.

* `season`: Datos de las temporadas asociadas a cada programa de TV.

* `view_summary`: Métricas de visualización y rendimiento de películas o temporadas.

Revisa con detalle su esquema para que comprendas cómo se relacionan las tablas anteriores.

**NOTA IMPORTANTE:** Asegúrate de responder *explícitamente* todos los cuestionamientos.

`PyMySQL` es una librería escrita en Python puro que funciona como conector (*driver*) para motores de bases de datos MySQL, permitiendo abrir conexiones, ejecutar consultas SQL y recuperar resultados directamente desde programas en Python.

In [158]:
pip install pymysql

Requirement already satisfied: pymysql in /usr/local/lib/python3.13/dist-packages (1.2.3)

`SQLAlchemy` es una librería de Python que facilita la interacción con bases de datos y permite mantener un pool de conexiones eficiente, gestionar *commits* y *rollbacks* de forma automática y asegurar que múltiples conexiones simultáneas se manejen de manera segura, incluso cuando se ejecutan consultas SQL “puras”

In [159]:
# Importa las librerías necesarias
import pymysql
import sqlalchemy as sqla
import pandas as pd

Se crea una conexión (`conn`) para luego invocar declaraciones SQL.

In [160]:
# motor+driver://usuarioBD:clave@ipHostDBMS:puerto/esquema
# pool_recycle controla el tiempo máximo de vida de una conexión en el pool (3600 segundos = 1 hora)
db = sqla.create_engine('mysql+pymysql://mnaTC5053User:mnaTC5053Pass!@20.127.169.219:3306/Netflix', pool_recycle=3600)
conn = db.connect()

Para que tus consultas sean más legibles y fáciles de mantener, puedes usar este formato multilínea con comillas triples y `sqla.text()`. Por ejemplo:

```
query = sqla.text("""
  SELECT ---
  FROM ---
  WHERE ---
""")
pd.read_sql(query, conn)
```

1.	Extrae toda la información de las películas que duran más de 5 horas.

In [161]:
query = sqla.text("""
  SELECT *
  FROM movie
  where runtime > 300
""")

In [162]:
df=pd.read_sql(query, conn)
df

,id,created_date,modified_date,available_globally,locale,original_title,release_date,runtime,title
0,5793,2024-01-01,2024-01-01,b'\x00',None,日本統一シリーズ: 映画シリーズ,None,3892,Nihontouitsu Series: Film Series
1,5794,2024-01-01,2024-01-01,b'\x00',None,釣りバカ日誌: 映画シリーズ,None,2120,Free and Easy Series: Film Series
2,5874,2024-01-01,2024-01-01,b'\x01',None,None,2021-08-06,312,Navarasa: Limited Series
3,9729,2024-01-01,2024-01-01,b'\x00',None,織田同志会 織田征仁: 映画シリーズ,None,710,Seiji Oda: Film Series
4,9730,2024-01-01,2024-01-01,b'\x00',None,キングダム～首領になった男～: 映画シリーズ,None,427,Kingdom ~ The Man Who Became the Top ~: Film S...

2.	¿Cuál es el porcentaje de películas disponibles únicamente en EU en relación con el total, excluyendo los valores `NULL`? La consulta SQL debe entregar directamente el porcentaje final. No se deben devolver resultados parciales para realizar el cálculo en Python.

In [163]:
query = sqla.text("""
  SELECT (COUNT(IF(available_globally = 0, 1, NULL)) / COUNT(*))*100 as porcentaje_peliculas_eu
  FROM movie
  where available_globally is not null
""")

In [164]:
df=pd.read_sql(query, conn)
df

   porcentaje_peliculas_eu
0                  83.5717

El porcentaje es 83.57%

3.	¿Cuáles son los idiomas o regiones originales en la tabla de películas?

In [165]:
query = sqla.text("""
  SELECT locale,count(*)
  FROM movie
  group by locale
""")

In [166]:
df=pd.read_sql(query, conn)
df

  locale  count(*)
0   None     11255
1     en       532

Solo en (inglés)

* ¿Cuántos registros tienen el campo `locale` con valor `NULL`? (NULL en SQL ⇔ None en Python)

In [167]:
query = sqla.text("""
  SELECT count(*)
  FROM movie
  where locale is null
""")

In [168]:
df=pd.read_sql(query, conn)
df

   count(*)
0     11255

11255 registros

4.	Asumiendo que los valores `NULL` en `locale` corresponden a otro idioma (diferente del inglés), el título original de la película NO debería coincidir con el título principal en dichos registros.
* Determina cuántas películas tienen títulos diferentes en estos dos campos (`title` y `original_title`).
*  ¿Coinciden los resultados (cantidad de `NULL` y títulos diferentes)? Si no es así, identifica qué características tienen los registros restantes.
* Finalmente, concluye si la suposición de que los valores `NULL` en `locale` indican que la película está en otro idioma es válida.

In [169]:
#conn.rollback()

In [170]:
#Validacion 1

query = sqla.text("""
  SELECT count(*)
  FROM movie
  where title != original_title
""")

df=pd.read_sql(query, conn)
df

   count(*)
0      3947

In [171]:
#Validacion 2

query = sqla.text("""
  SELECT count(*)
  FROM movie
  where locale is null
""")

df=pd.read_sql(query, conn)
df

   count(*)
0     11255

La suposicion no es valida ya que son diferentes los resultados

5.	Determina el título de la película que ha permanecido más tiempo en el top 10.

In [172]:
#conn.rollback()

In [173]:

query = sqla.text("""
  SELECT movie.original_title, movie.title,view_summary.cumulative_weeks_in_top10
  FROM view_summary
  INNER JOIN movie ON view_summary.movie_id = movie.id
  where view_summary.cumulative_weeks_in_top10 is not null
  ORDER BY view_summary.cumulative_weeks_in_top10 desc
""")

df=pd.read_sql(query, conn)
df

,original_title,title,cumulative_weeks_in_top10
0,None,The Boss Baby,22
1,None,The Boss Baby,21
2,None,The Super Mario Bros. Movie,21
3,None,Under Paris,21
4,None,The Boss Baby,20
...,...,...,...
2354,None,Take Care of Maya,1
2355,None,King of Clones,1
2356,None,Black Clover: Sword of the Wizard King,1
2357,None,The Mule,1
2358,None,47 Ronin,1

La pelicula es The Boss Baby

6.	Identifica los 5 programas de TV con mayor cantidad de temporadas.

In [174]:
#conn.rollback()

In [175]:

query = sqla.text("""
  SELECT tv_show.title, count(distinct(season.id))
  FROM season
  INNER JOIN tv_show ON season.tv_show_id = tv_show.id
  group by tv_show.title
  order by count(distinct(season.id)) desc
  limit 5
""")

df=pd.read_sql(query, conn)
df

                               title  count(distinct(season.id))
0                     Grey's Anatomy                          20
1                   Naruto Shippuden                          20
2                   Heartland (2007)                          17
3  It's Always Sunny in Philadelphia                          16
4                               NCIS                          15

Son: Grey's Anatomy, Naruto Shippuden, Heartland (2007), It's Always Sunny in Philadelphia y NCIS

7.	¿Cuáles son los intervalos de fechas de los resúmenes en la tabla `view_summary` de los períodos (`duration`) semestrales?

In [176]:

query = sqla.text("""
  SELECT distinct start_date,end_date
  FROM view_summary
  where duration = 'SEMI_ANNUALLY'
""")

df=pd.read_sql(query, conn)
df

   start_date    end_date
0  2024-01-01  2024-06-30
1  2023-07-01  2023-12-31

Los intervalos son 2024-01-01 al 2024-06-30 y 2023-07-01 al 2023-12-31

8.	Ordena las temporadas de *Grey's Anatomy* según la cantidad de vistas registradas en el primer período semestral de 2024.
* ¿Cómo interpretarías los resultados obtenidos?

In [177]:

query = sqla.text("""
  SELECT s.season_number,sum(views)
  FROM tv_show ts
  inner join season s on ts.id = s.tv_show_id
  inner join view_summary vs on s.id = vs.season_id
  where ts.title = 'Grey''s Anatomy' and vs.duration = 'SEMI_ANNUALLY' and vs.start_date = '2024-01-01'
  group by s.season_number
  order by sum(views) desc
""")

df=pd.read_sql(query, conn)
df

    season_number  sum(views)
0               1   3600000.0
1               2   3100000.0
2               3   2900000.0
3               5   2900000.0
4               4   2900000.0
5               6   2800000.0
6               7   2700000.0
7               8   2600000.0
8               9   2500000.0
9              10   2400000.0
10             11   2200000.0
11             12   2000000.0
12             13   2000000.0
13             14   2000000.0
14             19   2000000.0
15             15   1900000.0
16             16   1800000.0
17             18   1700000.0
18             17   1700000.0
19             20    100000.0

Interpreto que mientras iban saliendo más y más temporadas estas iban teniendo cada vez menos vistas

9.	Todas las consultas anteriores podrían hacerse también con la lógica relacional implementada en Pandas, que permite replicar la mayoría de las operaciones de SQL. Si los dataframes se han llenado como sigue, resuelve la consulta 8 utilizando las funciones de Pandas.

In [178]:
#conn.rollback()

In [179]:
tv_show = pd.read_sql(sqla.text('SELECT * FROM tv_show'), conn)
season = pd.read_sql(sqla.text('SELECT * FROM season'), conn)
view_summary = pd.read_sql(sqla.text('SELECT * FROM view_summary'), conn)

In [180]:
df_tv_show_season = pd.merge(tv_show, season, left_on="id",right_on="tv_show_id")
df_final = pd.merge(df_tv_show_season, view_summary, left_on="id_y", right_on="season_id", how="inner")
df_final.head()

,id_x,created_date_x,modified_date_x,available_globally,locale,original_title_x,release_date_x,title_x,id_y,created_date_y,...,modified_date,cumulative_weeks_in_top10,duration,end_date,hours_viewed,start_date,view_rank,views,movie_id,season_id
0,1,2024-01-01,2024-01-01,b'\x01',en,None,None,Fool Me Once,1,2024-01-01,...,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,689500000,2024-01-01,NaN,107500000,NaN,1.0
1,1,2024-01-01,2024-01-01,b'\x01',en,None,None,Fool Me Once,8091,2024-01-01,...,2024-01-01,8.0,WEEKLY,2024-03-24,8100000,2024-03-18,9.0,1300000,NaN,8091.0
2,1,2024-01-01,2024-01-01,b'\x01',en,None,None,Fool Me Once,8091,2024-01-01,...,2024-01-01,7.0,WEEKLY,2024-02-18,15000000,2024-02-12,5.0,2300000,NaN,8091.0
3,1,2024-01-01,2024-01-01,b'\x01',en,None,None,Fool Me Once,8091,2024-01-01,...,2024-01-01,6.0,WEEKLY,2024-02-11,21100000,2024-02-05,5.0,3300000,NaN,8091.0
4,1,2024-01-01,2024-01-01,b'\x01',en,None,None,Fool Me Once,8091,2024-01-01,...,2024-01-01,5.0,WEEKLY,2024-02-04,33000000,2024-01-29,4.0,5100000,NaN,8091.0

In [181]:
from datetime import date

df_final = df_final[(df_final['title_x'] == "Grey's Anatomy") & (df_final['duration'] == 'SEMI_ANNUALLY') & (df_final['start_date'] == date(2024, 1, 1))]

df_final.head()

,id_x,created_date_x,modified_date_x,available_globally,locale,original_title_x,release_date_x,title_x,id_y,created_date_y,...,modified_date,cumulative_weeks_in_top10,duration,end_date,hours_viewed,start_date,view_rank,views,movie_id,season_id
2309,347,2024-01-01,2024-01-01,b'\x00',None,None,None,Grey's Anatomy,575,2024-01-01,...,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,23400000,2024-01-01,NaN,3600000,NaN,575.0
2311,347,2024-01-01,2024-01-01,b'\x00',None,None,None,Grey's Anatomy,685,2024-01-01,...,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,60600000,2024-01-01,NaN,3100000,NaN,685.0
2313,347,2024-01-01,2024-01-01,b'\x00',None,None,None,Grey's Anatomy,742,2024-01-01,...,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,53700000,2024-01-01,NaN,2900000,NaN,742.0
2315,347,2024-01-01,2024-01-01,b'\x00',None,None,None,Grey's Anatomy,743,2024-01-01,...,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,49300000,2024-01-01,NaN,2900000,NaN,743.0
2317,347,2024-01-01,2024-01-01,b'\x00',None,None,None,Grey's Anatomy,749,2024-01-01,...,2024-01-01,NaN,SEMI_ANNUALLY,2024-06-30,35300000,2024-01-01,NaN,2900000,NaN,749.0

In [182]:
df_final = (
    df_final
    .groupby('season_number')['views']
    .sum()
    .reset_index()
    .rename(columns={'views': 'sum_views'})
    .sort_values('sum_views', ascending=False)
)

df_final.head(20)

    season_number  sum_views
0             1.0    3600000
1             2.0    3100000
2             3.0    2900000
3             4.0    2900000
4             5.0    2900000
5             6.0    2800000
6             7.0    2700000
7             8.0    2600000
8             9.0    2500000
9            10.0    2400000
10           11.0    2200000
11           12.0    2000000
12           13.0    2000000
13           14.0    2000000
18           19.0    2000000
14           15.0    1900000
15           16.0    1800000
16           17.0    1700000
17           18.0    1700000
19           20.0     100000

`MySQL` es un sistema de gestión de bases de datos relacional, pero desde Python también es posible extraer información de bases de datos no relacionales, como `Firestore`, `MongoDB` o `Cassandra`, utilizando conectores o integraciones específicas. Esto permite combinar datos de diferentes fuentes según las necesidades del análisis o la aplicación.

En el siguiente ejercicio usarás un ejemplo con `Firestore` desde Python. Para ello utilizarás los módulos `credentials` y `firestore` de la biblioteca `firebase_admin`.

In [183]:
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

En `Firestore`, a diferencia de `MySQL` donde se utiliza un usuario y contraseña para conectarse, la autenticación se realiza mediante un archivo JSON que almacena las credenciales necesarias para acceder a la base de datos. Este archivo contiene las claves y la información de configuración que permiten a Python establecer la conexión de manera segura.

In [184]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [185]:
# Debes descargar el archivo de credenciales "consultancy.json" (disponible en las instrucciones de Canvas) y ubicarte en la carpeta donde lo almacenaste
import os
DIR = "/content/drive/MyDrive/Colab Notebooks/MNA/1er trimestre/Ciencia y analitica de datos/semana 3"
os.chdir(DIR)

In [186]:
# consultancy.json almacena la clave privada para autenticar una cuenta y autorizar el acceso a los servicios
# A través de la función Certificate(), se regresa una credencial inicializada, que puedes utilizar para crear una nueva instancia de la aplicación
cred = credentials.Certificate('consultancy.json')
firebase_admin.initialize_app(cred)
db = firestore.client()

10.	Investiga cómo leer la colección `EMPLOYEE` y mostrar su contenido en un dataframe. Asegúrate de incluir el `id` en el resultado

In [187]:
employees_ref = db.collection('EMPLOYEE')
print(employees_ref)

<google.cloud.firestore_v1.collection.CollectionReference object at 0x7a23d71350f0>

In [188]:
docs = employees_ref.stream()
print(docs)

<google.cloud.firestore_v1.stream_generator.StreamGenerator object at 0x7a23d7136780>

In [189]:
data = []
for doc in docs:
    record = doc.to_dict()
    record['id'] = doc.id
    data.append(record)

# Crear el DataFrame
df_employee = pd.DataFrame(data)

df_employee.head()

  emp_fname   emp_lname                    id              emp_hiredate
0     David      Senior  8LcLuxVHGAd2d9IQc5jF 1989-07-12 06:00:00+00:00
1   William  Smithfield  Fzd60D6Z2CU4n0wVV8YN 2004-06-04 05:00:00+00:00
2      John        News  lX5xuQ5w3i6ib2ExccWY 2000-11-08 06:00:00+00:00
3      June     Arbough  yocFj2lichOkbAj9NBfp 1996-12-01 06:00:00+00:00

In [190]:
firebase_admin.delete_app(firebase_admin.get_app())

---

**Declaración de uso de IA**

*   OpenAI. (2026). *ChatGPT (basado en GPT-4)* [Sonnet 4.5], utilizado para investigar acerca de bases de datos no relacionales. https://chat.openai.com/

---